name: Enforce Valid Repository Name

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  validate-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Repository Name
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # Define valid suffixes
          VALID_SUFFIXES=("backend" "middleware" "frontend")

          # Define valid project names
          VALID_PROJECTS=("middey" "nellalinksbs" "nellalinktest")

          # Define valid modules
          VALID_MODULES=("user-app" "admin-app" "kyc-verification" "validate-transaction")

          # Extract parts of the repository name
          SUFFIX=$(echo "$REPO_NAME" | cut -d- -f1)
          PROJECT=$(echo "$REPO_NAME" | cut -d- -f2)
          MODULE=$(echo "$REPO_NAME" | cut -d- -f3-)

          # Check if SUFFIX is valid
          if [[ ! " ${VALID_SUFFIXES[@]} " =~ " $SUFFIX " ]]; then
            echo "Error: Invalid suffix '$SUFFIX'. Must be one of: ${VALID_SUFFIXES[@]}."
            exit 1
          fi

          # Check if PROJECT is valid
          if [[ ! " ${VALID_PROJECTS[@]} " =~ " $PROJECT " ]]; then
            echo "Error: Invalid project name '$PROJECT'. Must be one of: ${VALID_PROJECTS[@]}."
            exit 1
          fi

          # Check if MODULE is valid
          if [[ ! " ${VALID_MODULES[@]} " =~ " $MODULE " ]]; then
            echo "Error: Invalid module name '$MODULE'. Must be one of: ${VALID_MODULES[@]}."
            exit 1
          fi

          echo "Repository name '$REPO_NAME' is valid."
